"""Added is_active for interviews

Revision ID: 1051bc9e44ab
Revises: 73fbc3c4cf4a
Create Date: 2025-05-21 13:52:15.514469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1051bc9e44ab'
down_revision: Union[str, None] = '73fbc3c4cf4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add column as nullable first
    op.add_column('interviews', sa.Column('is_active', sa.Boolean(), nullable=True))

    # Step 2: Set default value (e.g., True) for existing rows
    op.execute("UPDATE interviews SET is_active = TRUE")

    # Step 3: Alter column to be NOT NULL
    op.alter_column('interviews', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'is_active')
    # ### end Alembic commands ###
