"""Updated interview model (removed optional in fields)

Revision ID: c340707356ab
Revises: b0536649dc44
Create Date: 2025-05-13 14:13:04.775337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c340707356ab'
down_revision: Union[str, None] = 'b0536649dc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'job_position',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interviews', 'experience',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('interviews', 'tech_stack',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'tech_stack',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interviews', 'experience',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('interviews', 'job_position',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
